import { Metadata } from "next";
import { Raleway } from "next/font/google";
import "../styles/globals.css";
import Image from "next/image";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${raleway.className}`}>
        {children}

        <Image
          className="absolute bottom-10 left-0 right-0 mx-auto z-index-1 "
          src="/trinca-logo.svg"
          alt="trinca Logo"
          width={60}
          height={60}
        />
      </body>
    </html>
  );
}
